name: smartcalc # you probably want to 'snapcraft register <name>'
version: '0.2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple, fast and mostly Smart Calc # 79 char long summary
description: |
  Amazing calc which can solve different math problems.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: SmartCalc.png
type: app

name: smartcalc
apps:
  smartcalc:
    command: SmartCalc

parts:
  smartcalc:
    # See 'snapcraft plugins'
    plugin: autotools
    prepare:  |
      sudo mkdir -p /etc/SmartCalc/
    prepare:  |
      sudo apt-get install python3
      sudo apt-get install python3-pip
      sudo pip3 install colorama
    install:  |
      sudo mv -f SmartCalc /bin
      sudo mv -f SmartCalc.desktop /usr/share/applications
      sudo mv -f * /etc/SmartCalc
